version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: FASTAPI
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FF66fK0=
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:FF66fK0=@db:5432/FASTAPI

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi_app:
    build: .
    container_name: fastapi_expense_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:FF66fK0=@db:5432/FASTAPI
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
