"""Add user_id to expenses

Revision ID: 08adbcaa1985
Revises: 
Create Date: 2025-07-07 17:08:12.193062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08adbcaa1985'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'])
    op.add_column('incomes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incomes', 'users', ['user_id'], ['id'])
    op.add_column('savings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'savings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'savings', type_='foreignkey')
    op.drop_column('savings', 'user_id')
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.drop_column('incomes', 'user_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'user_id')
    # ### end Alembic commands ###
