name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@<full-commit-SHA>


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@9c16076b5ccae4bbf73c67236b55ca48cc099216

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Send deploy command to EC2 via SSM
        run: |
          aws ssm send-command \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy backend" \
            --parameters 'commands=["cd /home/ubuntu/smart-library && git pull origin main && docker compose up -d --build"]'
